SQLALCHEMY_DATABASE_URI = 'sqlite:///mc.db'
SQLALCHEMY_TRACK_MODIFICATIONS = True
DEBUG = True
SECRET_KEY = 'development key'
USERNAME = 'admin'
PASSWORD = 'default'
MAX_X = 30
MAX_Y = 20
GRAPH_WIDTH = 800
GRAPH_HEIGHT = 400

